// Generated by scripts/generate-docs-registry.ts. Do not edit by hand.

export interface DocPage {
  slug: string;
  title: string;
  description: string;
  sourcePath: string;
  loadMarkdown: () => Promise<string>;
}

export interface DocNavSection {
  title: string;
  slugs: readonly string[];
}

export const DOC_PAGES: readonly DocPage[] = [
  {
    slug: "overview",
    title: "Overview",
    description: "Install BlazePlot, create your first chart, and understand the main tradeoffs.",
    sourcePath: "docs/overview.md",
    loadMarkdown: () => import("../../docs/overview.md?raw").then((module) => module.default),
  },
  {
    slug: "docs-map",
    title: "Docs map",
    description: "Reader paths, page ownership, and where each documentation topic belongs.",
    sourcePath: "docs/README.md",
    loadMarkdown: () => import("../../docs/README.md?raw").then((module) => module.default),
  },
  {
    slug: "examples",
    title: "Examples",
    description: "Copy-paste patterns for chart setup, plugins, data feeds, and exports.",
    sourcePath: "docs/examples.md",
    loadMarkdown: () => import("../../docs/examples.md?raw").then((module) => module.default),
  },
  {
    slug: "framework-integration",
    title: "Frameworks",
    description: "Use BlazePlot with React, Vue, Svelte, SSR frameworks, and a no-WebGL2 fallback.",
    sourcePath: "docs/framework-integration.md",
    loadMarkdown: () => import("../../docs/framework-integration.md?raw").then((module) => module.default),
  },
  {
    slug: "live-data",
    title: "Live data",
    description: "Streaming appends, fixed-rate shortcuts, sample updates, and follow-latest behavior.",
    sourcePath: "docs/live-data.md",
    loadMarkdown: () => import("../../docs/live-data.md?raw").then((module) => module.default),
  },
  {
    slug: "data-semantics",
    title: "Data",
    description: "How BlazePlot interprets series data, ordering, ring buffers, and sampling.",
    sourcePath: "docs/data-semantics.md",
    loadMarkdown: () => import("../../docs/data-semantics.md?raw").then((module) => module.default),
  },
  {
    slug: "performance-recipes",
    title: "Performance",
    description: "Practical guidance for streaming, LOD, dense data, and browser budgets.",
    sourcePath: "docs/performance-recipes.md",
    loadMarkdown: () => import("../../docs/performance-recipes.md?raw").then((module) => module.default),
  },
  {
    slug: "benchmarks",
    title: "Benchmarks",
    description: "How BlazePlot compares with uPlot and Chart.js, at a glance.",
    sourcePath: "docs/benchmarks.md",
    loadMarkdown: () => import("../../docs/benchmarks.md?raw").then((module) => module.default),
  },
  {
    slug: "benchmark-results",
    title: "Benchmark results",
    description: "Every metric of every benchmark scenario, with spreads and the change since the baseline.",
    sourcePath: "docs/benchmark-results.md",
    loadMarkdown: () => import("../../docs/benchmark-results.md?raw").then((module) => module.default),
  },
  {
    slug: "built-in-plugins",
    title: "Plugins",
    description: "Use the optional interaction, tooltip, legend, annotation, selection, crosshair, navigator, accessibility, and flame graph plugins.",
    sourcePath: "docs/built-in-plugins.md",
    loadMarkdown: () => import("../../docs/built-in-plugins.md?raw").then((module) => module.default),
  },
  {
    slug: "theming-and-layout",
    title: "Theme & layout",
    description: "Chart theme tokens, axis placement, gutters, and responsive layout behavior.",
    sourcePath: "docs/theming-and-layout.md",
    loadMarkdown: () => import("../../docs/theming-and-layout.md?raw").then((module) => module.default),
  },
  {
    slug: "plugin-authoring",
    title: "Author plugins",
    description: "Build chart plugins on the stable plugin context: mount slots, pointer claims, lifecycle hooks, and typed events.",
    sourcePath: "docs/plugin-authoring.md",
    loadMarkdown: () => import("../../docs/plugin-authoring.md?raw").then((module) => module.default),
  },
  {
    slug: "troubleshooting",
    title: "Troubleshooting",
    description: "Fix blank charts, live viewport issues, performance drift, and common React mistakes.",
    sourcePath: "docs/troubleshooting.md",
    loadMarkdown: () => import("../../docs/troubleshooting.md?raw").then((module) => module.default),
  },
  {
    slug: "browser-support",
    title: "Browser",
    description: "Runtime requirements and WebGL2 support expectations.",
    sourcePath: "docs/browser-support.md",
    loadMarkdown: () => import("../../docs/browser-support.md?raw").then((module) => module.default),
  },
  {
    slug: "migrating-to-1.0",
    title: "Migrating to 1.0",
    description: "Breaking changes and new features from 0.x to 1.0 with before and after code and an upgrade checklist.",
    sourcePath: "docs/migrating-to-1.0.md",
    loadMarkdown: () => import("../../docs/migrating-to-1.0.md?raw").then((module) => module.default),
  },
  {
    slug: "versioning-and-migration",
    title: "Migration",
    description: "Semver policy, migration expectations, and public API stability notes.",
    sourcePath: "docs/versioning-and-migration.md",
    loadMarkdown: () => import("../../docs/versioning-and-migration.md?raw").then((module) => module.default),
  },
  {
    slug: "stability",
    title: "Stability",
    description: "What is stable, experimental, and internal in each BlazePlot export and subpath.",
    sourcePath: "docs/stability.md",
    loadMarkdown: () => import("../../docs/stability.md?raw").then((module) => module.default),
  },
  {
    slug: "error-handling",
    title: "Errors",
    description: "Errors thrown, console output, and how invalid data, viewports, and renderer failures are handled.",
    sourcePath: "docs/error-handling.md",
    loadMarkdown: () => import("../../docs/error-handling.md?raw").then((module) => module.default),
  },
  {
    slug: "accessibility",
    title: "Accessibility",
    description: "Chart semantics, the a11y plugin (data table, keyboard inspection), key map, high contrast, and known limits.",
    sourcePath: "docs/accessibility.md",
    loadMarkdown: () => import("../../docs/accessibility.md?raw").then((module) => module.default),
  },
  {
    slug: "api-reference",
    title: "API reference",
    description: "Generated package entry point, symbol, bundle size, and public API reference.",
    sourcePath: "docs/api-reference.md",
    loadMarkdown: () => import("../../docs/api-reference.md?raw").then((module) => module.default),
  },
  {
    slug: "release-and-benchmarks",
    title: "Release",
    description: "Release flow, benchmark commands, and how to read generated performance tables.",
    sourcePath: "docs/release-and-benchmarks.md",
    loadMarkdown: () => import("../../docs/release-and-benchmarks.md?raw").then((module) => module.default),
  },
  {
    slug: "roadmap",
    title: "Roadmap",
    description: "Current status, near-term priorities, and non-goals for BlazePlot.",
    sourcePath: "docs/roadmap.md",
    loadMarkdown: () => import("../../docs/roadmap.md?raw").then((module) => module.default),
  },
  {
    slug: "documentation-contributions",
    title: "Docs process",
    description: "How to make BlazePlot docs concrete, source-checked, and useful.",
    sourcePath: "docs/documentation-contributions.md",
    loadMarkdown: () => import("../../docs/documentation-contributions.md?raw").then((module) => module.default),
  },
];

export const DOC_NAV_SECTIONS: readonly DocNavSection[] = [
  { title: "Start", slugs: ["overview","docs-map","examples","framework-integration"] },
  { title: "Data and performance", slugs: ["live-data","data-semantics","performance-recipes","benchmarks","benchmark-results"] },
  { title: "UI", slugs: ["built-in-plugins","theming-and-layout","plugin-authoring"] },
  { title: "Reference", slugs: ["troubleshooting","browser-support","migrating-to-1.0","versioning-and-migration","stability","error-handling","accessibility","api-reference"] },
] as const;

export function getDocPage(slug: string): DocPage | undefined {
  return DOC_PAGES.find((page) => page.slug === slug);
}
