#!/usr/bin/env bun
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

interface DocPageMeta {
  slug: string;
  title: string;
  description: string;
  sourcePath: string;
  section: string;
  order: number;
  nav?: boolean;
}

const root = resolve(new URL("..", import.meta.url).pathname);
const pagesPath = resolve(root, "docs/pages.json");
const outputPath = resolve(root, "website/src/docs.ts");

function importName(slug: string): string {
  return slug.replace(/[^a-zA-Z0-9]+(.)?/g, (_, chr: string | undefined) => chr ? chr.toUpperCase() : "").replace(/^[0-9]/, "_$&");
}

function readPages(): DocPageMeta[] {
  const pages = JSON.parse(readFileSync(pagesPath, "utf8")) as DocPageMeta[];
  const seen = new Set<string>();
  for (const page of pages) {
    if (!page.slug || !page.title || !page.description || !page.sourcePath || !page.section) {
      throw new Error(`Invalid docs page metadata: ${JSON.stringify(page)}`);
    }
    if (seen.has(page.slug)) throw new Error(`Duplicate docs slug: ${page.slug}`);
    seen.add(page.slug);
    if (!existsSync(resolve(root, page.sourcePath))) throw new Error(`Missing docs source for ${page.slug}: ${page.sourcePath}`);
  }
  return pages.slice().sort((a, b) => a.order - b.order || a.slug.localeCompare(b.slug));
}

function render(pages: readonly DocPageMeta[]): string {
  const imports = pages
    .map((page) => `import ${importName(page.slug)} from "../../${page.sourcePath}?raw";`)
    .join("\n");
  const pageEntries = pages.map((page) => {
    const name = importName(page.slug);
    return `  {\n    slug: ${JSON.stringify(page.slug)},\n    title: ${JSON.stringify(page.title)},\n    description: ${JSON.stringify(page.description)},\n    sourcePath: ${JSON.stringify(page.sourcePath)},\n    markdown: ${name},\n  },`;
  }).join("\n");

  const sections = Array.from(new Set(pages.filter((page) => page.nav !== false).map((page) => page.section)));
  const navEntries = sections.map((section) => {
    const slugs = pages.filter((page) => page.nav !== false && page.section === section).map((page) => page.slug);
    return `  { title: ${JSON.stringify(section)}, slugs: ${JSON.stringify(slugs)} },`;
  }).join("\n");

  return `// Generated by scripts/generate-docs-registry.ts. Do not edit by hand.\n${imports}\n\nexport interface DocPage {\n  slug: string;\n  title: string;\n  description: string;\n  sourcePath: string;\n  markdown: string;\n}\n\nexport interface DocNavSection {\n  title: string;\n  slugs: readonly string[];\n}\n\nexport const DOC_PAGES: readonly DocPage[] = [\n${pageEntries}\n];\n\nexport const DOC_NAV_SECTIONS: readonly DocNavSection[] = [\n${navEntries}\n] as const;\n\nexport function getDocPage(slug: string): DocPage | undefined {\n  return DOC_PAGES.find((page) => page.slug === slug);\n}\n`;
}

const check = process.argv.includes("--check");
const next = render(readPages());
const current = existsSync(outputPath) ? readFileSync(outputPath, "utf8") : "";
if (check) {
  if (current !== next) {
    console.error("website/src/docs.ts is stale. Run `bun scripts/generate-docs-registry.ts`.");
    process.exit(1);
  }
  console.log("Docs registry is fresh.");
} else {
  writeFileSync(outputPath, next);
  console.log("Generated website/src/docs.ts from docs/pages.json.");
}
